[Variables]

; --- PROGRESS BAR
orientation_progressbar=Vertical
width_progressbar=1.92
height_progressbar=96
xpos_progressbar=84.48
ypos_progressbar=11.52

; --- NOW
xpos_now=76.8
ypos_now=42.24

; --- PLAYING
xpos_playing=76.8
ypos_playing=55.68

; --- NOW PLAYING FOR CENTER
xpos_nowplaying=264.96
ypos_nowplaying=17.28

; --- UPDATE INDICATOR
xpos_indicator=26.88
ypos_indicator=45.12

; --- TIME
xpos_time=76.8
ypos_time=13.44

; --- PROGRESS
xpos_progress=76.8
ypos_progress=24.96

; --- SETTINGS
xpos_settings=48
ypos_settings=24.96

; --- PLAY BUTTON
xpos_play=46.08
ypos_play=90.24

; --- PREVIOUS BUTTON
xpos_prev=76.8
ypos_prev=76.8

; --- NEXT BUTTON
xpos_next=76.8
ypos_next=90.24

; --- INTERFACE
align_interface=Right

; --- REGULAR: CONTAINERS
xpos_container_reg=94.08
ypos_containertop_reg=21.12
ypos_containerbtm_reg=54.72
width_container_reg=417.6

; --- STANDARD: CONTAINERS
width_container_std=417.6
width_container_scroll=491.52
height_container_std=42.24

; --- CONTAINER TEXT
xpos_containertext=0
ypos_containertextbtm=0
ypos_containertexttop=46.08
align_containertext_supposed=Left

; PURE --------------

; --- PURE, UPDATE INDICATOR
pure_xpos_indicator=0

; --- PURE, REGULAR: CONTAINERS
pure_ypos_containertop_reg=17.28
pure_ypos_containerbtm_reg=50.88
