[Variables]

skinSize=(#SCREENAREAHEIGHT#*0.5)
lastSetWidth=384

Player=Spotify
alignRight=0

activePlugin=NowPlaying

topTextWidth=551
bottomTextWidth=160

; 0 = MUSIC, 2 = WEBNOWPLAYING
MusicSwitch=2
playerController=StateButton2
currentlySetName=WebNowPlaying
currentlySetPlayer=WMP

adaptiveHideActive=0

stowAway=0
stowAwayName=NULL

topText=mArtist
bottomText=mTitle

disableScroll=0

removeExtraFromText=0

thinFont=Metropolis Extra Light
thickFont=Metropolis Medium
controlsFont=Metropolis Medium

mediaTextPositionHor=0
mediaTextAlignment=LeftBottom
mediaTextAlignmentPure=Left
interfaceTextAlignment=Right
nowTextPositionHor=71.04
hairlinePositionHor=82.56
topTextPositionHor=95.04
playCtrlPositionHor=38.4
settingsTextPositionHor=44.16
indicatorPositionHor=26.88
indicatorPositionHorPure=15.36
conflictIndicatorPositionHor=11.52
conflictIndicatorPositionHorPure=30.72
